### ISSUE TITLE
USB problem in the VM

### ISSUE THREAD

**Issue by krichardsson** [bitcraze/bitcraze-vm#31]
We have seen USB communication problems in the virtual machine. When using the python client, the Crazyradio and a Crazyflie the symptoms are loss of connectivity and general communication problems between the client and the Crazyflie. 
The problem has been observed on Windows, OSX and linux when using Virtual Box as the virtualization environment. As far as we know this problem is related to Virtual Box and seems to have been introduced at some point the last few months. It has not been observed in native installations. 

Workaround: Run the client natively without the VM. See instruction in [the getting started](https://www.bitcraze.io/getting-started-with-the-crazyflie-2-0/#inst-comp) and <https://github.com/bitcraze/crazyflie-clients-python/blob/master/README.md>.

This problem needs further investigation to reach a better understanding.

**Comment by krichardsson** [comment]
A possible workaround (that also has some benefits compared to the VM) would be to create an ISO that can be written to a USB stick to be used as a bootable drive.  

Thanks Patric H for the idea!

**Comment by krichardsson** [comment]
# Possible workaround
It seems as setting the USB port to USB3 in the VM improves the situation for some users.

The setting can be found in the settings for the VM, the Ports section, the USB tab

**Comment by ataffanel** [comment]
Lets switch to USB3 for the next release. This should be done in the build script: the VM should be created with USB3 controller enabled by default.
