### ISSUE TITLE
Upgraded VM running 64bit (?)

### ISSUE THREAD

**Issue by Woody7777** [bitcraze/bitcraze-vm#35]
Will the upgraded VM run XUbuntu 18.04 LTS **64 bit**?

I think the tools in use are available and / or running on a 64bit system, however, e.g. [Gitkraken ](https://www.gitkraken.com/) is not available for 32bit.

**Comment by ataffanel** [comment]
That is the question :-).

I am currently doing test with the 64bit version of XUbuntu. The positive things is that it might allow to support more software. One negative point of 64Bit is that it would use more RAM.

If there is software that starts to be released only for 64Bits maybe it is a good reason to switch to 64Bits.
