### ISSUE TITLE
files.bitcraze.se: Please provide releases over HTTPS 

### ISSUE THREAD

**Issue by dlitz** [bitcraze/bitcraze-vm#37]
Could you please provide your VM images over HTTPS instead of the insecure HTTP protocol?  In 2019, it's very easy and doesn't cost anything.

See instructions here: https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04

**Comment by krichardsson** [comment]
Hi!
yeah, you are totally right. This server has not been the highest priority but should of course be fixed at some point. 

Thanks!

**Comment by ataffanel** [comment]
I just enabled lets-encrypt on files.bitcraze.se using certbot. Thanks for the report!

**Comment by dlitz** [comment]
Thanks!  You may want to edit the links on the wiki as well: https://wiki.bitcraze.io/projects:virtualmachine:index#download
