### ISSUE TITLE
vm import error

### ISSUE THREAD

**Issue by YuchaoS** [bitcraze/bitcraze-vm#38]
Mac OSX 10.14.4
VirtualBox 6.06
When I double click the 2018.12.ova.
ERROR
Result Code: | NS_ERROR_INVALID_ARG (0x80070057)
how can I fix this bug.

**Comment by ataffanel** [comment]
A quick googling shows that it might be that you do not have enough space on your harddrive: https://www.virtualbox.org/ticket/18343

**Comment by YuchaoS** [comment]
> A quick googling shows that it might be that you do not have enough space on your harddrive: https://www.virtualbox.org/ticket/18343

Thanks for your reply,I fixed this by importing it from vm workstation on windows and then exporting it's ovf to the vm on mac.
