### ISSUE TITLE
Eclipse's broken openOCD and GDB links should be fixed

### ISSUE THREAD

**Issue by knmcguire** [bitcraze/bitcraze-vm#39]
The debug configuration settings of eclipse seems to not point to the right location of OpenOCD ( should be: /usr/bin/openocd) and GDB (should be: /home/bitcraze/bin/arm-none-eabi-gdb)

**Comment by NicksonYap** [comment]
Confirmed that this solves the issue, how to apply this fix to the repo?

**Comment by NicksonYap** [comment]
For those who cannot wait for new release or re-configure a new VM

Change `openocd_path`
from  `/opt/gnuarmeclipse/openocd/0.9.0-201505190955/bin` 
to `/usr/bin`

steps:

![image](https://user-images.githubusercontent.com/5380731/65154696-8b475680-da5e-11e9-8748-ff85bb5e7987.png)

**Comment by jonasdn** [comment]
New VM version uses vscode for debugging.
