### ISSUE TITLE
cflib should be installed by standard

### ISSUE THREAD

**Issue by knmcguire** [bitcraze/bitcraze-vm#42]
Also, installing cflib by pip3 install cflib still results in the examples not finding the library

**Comment by ataffanel** [comment]
Cflib is installed in edit mode from the repos when the VM is created: https://github.com/bitcraze/bitcraze-vm/blob/master/provision.sh#L95. Hence all example should work using python 3 out of the box.

Is there a problem running the examples?

**Comment by knmcguire** [comment]
False alarm, installed the VM again and did update projects. No problem anymore. I'll close the issue
