### ISSUE TITLE
ISO not downloaded

### ISSUE THREAD

**Issue by NicksonYap** [bitcraze/bitcraze-vm#43]
`$ISO_FILE` and `$ISO_URL` was not specified and used in 
https://github.com/bitcraze/bitcraze-vm/blob/master/createBitcrazeVM.sh#L24-L31

So Packer ends with an error

```
Running packer...
OVA file not found. Starting VM creation...
virtualbox-iso output will be in this color.

Build 'virtualbox-iso' errored: Failed creating VirtualBox driver: exec: "VBoxManage": executable file not found in $PATH

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Failed creating VirtualBox driver: exec: "VBoxManage": executable file not found in $PATH

==> Builds finished but no artifacts were created.
Starting VM provisioning...
```

**Comment by ataffanel** [comment]
Where are you running the script? I just tested and building the VM works for me.

From the print-out you sent it looks like packer cannot run Virtualbox and that is the reason it is failing.

**Comment by NicksonYap** [comment]
@ataffanel 

this is the full output:

```
seamless@ubuntu:~/Projects/bitcraze-vm$ ./createBitcrazeVM.sh
 not found. Starting download...
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
Packer already installed. Continuing...
contentForVM/gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2 found. Continuing...
contentForVM/eclipse-cpp-2018-09-linux-gtk-x86_64.tar.gz found. Continuing...
contentForVM/ilg.gnuarmeclipse.repository-2.12.1-201604190915.zip found. Continuing...
contentForVM/gnuarmeclipse-openocd-debian32-0.9.0-201505190955.tgz found. Continuing...
~/Projects/bitcraze-vm ~/Projects/bitcraze-vm
Compressing eclipse-project-files.tar.gz
~/Projects/bitcraze-vm
Running packer...
OVA file not found. Starting VM creation...
virtualbox-iso output will be in this color.

Build 'virtualbox-iso' errored: Failed creating VirtualBox driver: exec: "VBoxManage": executable file not found in $PATH

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Failed creating VirtualBox driver: exec: "VBoxManage": executable file not found in $PATH

==> Builds finished but no artifacts were created.
Starting VM provisioning...
virtualbox-ovf output will be in this color.

1 error(s) occurred:

* source_path is invalid: stat output-virtualbox-iso/BitcrazeVM.ova: no such file or directory
```

Note that is just says 
```
not found. Starting download...
wget: missing URL
```

This is where I believe there is no url given to download the ISO, causing packer to have an error

**Comment by ataffanel** [comment]
I do not think the wget error is the problem here. The wget error is most likely something left from a previous version, this iso is not used anywhere in the script: https://github.com/bitcraze/bitcraze-vm/blob/master/createBitcrazeVM.sh#L24-L31. I am going to remove it.

I sill think the problem is with vboxmanage, from your console:
```
--> virtualbox-iso: Failed creating VirtualBox driver: exec: "VBoxManage": executable file not found in $PATH
```
The likely reason is that you do not have virtualbox installed. On my machine after installing Virtualbox I can run VBoxManage from the console:
```bash
$ VBoxManage --version
5.2.34r133893
```
You should have both VirtualBox and the virtualbox extension installed. In my test I found that virtualbox 6.0 did not work so 5.2 needs to be installed, see #45.

**Comment by NicksonYap** [comment]
Ah, I wasn't aware that VirtualBox needs to be installed on the build host

I'll try that out
