### ISSUE TITLE
VM build not working with VirtualBox 6.0

### ISSUE THREAD

**Issue by ataffanel** [bitcraze/bitcraze-vm#45]
The VM build does not seems to work with VirtualBox 6.0 apparently due to change in the VBoxManage command line arguments. Until this is fixed, VirtualBox 5.2 needs to be used: https://www.virtualbox.org/wiki/Download_Old_Builds_5_2.

**Comment by knmcguire** [comment]
this no longer seems to hold. Been using 6.1 and up for a while now!
