### ISSUE TITLE
The VM cannot build the Crazyflie firmware using GCC7

### ISSUE THREAD

**Issue by ataffanel** [bitcraze/bitcraze-vm#46]
The version of arm-none-eabi-gcc contained in the VM 2018.12 is not able to compile the Crazyflie firmware.

The solution is to update to gcc8 when we make a new version of the VM

In the mean-time the current VM can be updated to use GCC8 by typing the following commande in a console:
``` bash
cd ~
wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/8-2019q3/RC1.1/gcc-arm-none-eabi-8-2019-q3-update-linux.tar.bz2?revision=c34d758a-be0c-476e-a2de-af8c6e16a8a2?product=GNU%20Arm%20Embedded%20Toolchain,64-bit,,Linux,8-2019-q3-update -O gcc-arm-none-eabi-8-2019-q3-update-linux.tar.bz2
sudo tar --strip-components=1 -xf gcc-arm-none-eabi-8-2019-q3-update-linux.tar.bz2
```

**Comment by ataffanel** [comment]
There is currently a bug in the Crazyflie firmware preventing it to be compiled with GCC9 (bitcraze/crazyflie-firmware#512). The plan is to wait for this bug to be fixed and then to update the VM with GCC9.

**Comment by jonasdn** [comment]
Fixed and a new VM is out: https://github.com/bitcraze/bitcraze-vm/releases/tag/2021.04
