### ISSUE TITLE
Added dependency in client not handled by update script

### ISSUE THREAD

**Issue by krichardsson** [bitcraze/bitcraze-vm#48]
The update scripts updates the source code in the repos but this is not enough when we add new pip dependencies in the client for instance. 
Dependency updates must now be done manually by the user and the documentation is (probably) not giving enough guidance.

It would be nice to address this problem some how.

See bitcraze/crazyflie-clients-python#451 for more details

**Comment by knmcguire** [comment]
This seems to be fixed in 966561be226bf24dce4e4e09548865333d9f6d0c
