### ISSUE TITLE
Upgrade the VM image to a later version (of everything)

### ISSUE THREAD

**Issue by krichardsson** [bitcraze/bitcraze-vm#49]
The VM image is outdated and need an update. 

There are many options but it should probably at least include upgrade of linux and adding VS code

**Comment by knmcguire** [comment]
I'm trying to build it locally with 20.04 iso, which is quite a difference from the 60 md xubuntu 18.04 before. Should we go to that path anyway or go for xubuntu again?

Also we should use visual code instead of eclipse now

**Comment by knmcguire** [comment]
probably sticking with xubuntu  (but then upgrading) is better in terms of resources. Also the automatic install needs too many changes so that will be to sensitive to errors

**Comment by jonasdn** [comment]
Released: https://github.com/bitcraze/bitcraze-vm/releases/tag/2021.04
