### ISSUE TITLE
How to upgrade to the 2021.01 release

### ISSUE THREAD

**Issue by krichardsson** [bitcraze/bitcraze-vm#50]
The VM is unfortunately becoming old and is in need of an upgrade (#49). 

Updating the source code to the 2021.01 release is unfortunately not as easy as running the "update all projects" script, the purpose of this issue is to document how to do it. 

If something is wrong or missing, please contribute!

From a terminal window:
1. upgrade pip ```pip3 install --upgrade pip```
1. Uninstall cfclient ```pip3 uninstall cfclient```
1. Re-install cfclient ```pip3 install cfclient```

if You want to run the client from source, first run the "update all projects" script and use ```pip3 install -e ~/projects/crazyflie-clients-python/``` and ```pip3 install -e ~/projects/crazyflie-lib-python/``` instead to install the client

**Comment by jonasdn** [comment]
Fixed in new release of VM: https://github.com/bitcraze/bitcraze-vm/releases/tag/2021.04
