### ISSUE TITLE
python dependencies errors

### ISSUE THREAD

**Issue by Iengq8** [bitcraze/bitcraze-vm#65]
when I am running the update all projects script I am faced with Python dependencies errors and the crazyflie client is no longer working

**Comment by krichardsson** [comment]
Hi,
most likely you need to upgrade pip, see https://github.com/orgs/bitcraze/discussions/545

**Comment by krichardsson** [comment]
Fixed in [release 2023.10](https://github.com/bitcraze/bitcraze-vm/releases/tag/2023.10)
