### ISSUE TITLE
Issues with Apple M1's

### ISSUE THREAD

**Issue by knmcguire** [bitcraze/bitcraze-vm#68]
Virtual box seems to not work well on the latests Mac computers. This has been reported in these discussions:

- https://github.com/orgs/bitcraze/discussions/1126
- https://github.com/orgs/bitcraze/discussions/688

This quote from @ataffanel indicates what was going on at the time and that we still have to check:

`I can observe the same things on our Mac M1. Virtualbox for Apple silicon is still in developer preview and is apparently not capable of running the Bitcraze VM yet. I tried with VMWare fusion but it was not able to run an x86 VM. So I am afraid that running the VM on apple silicon is not yet possible. We will update the documentation to reflect that.`

We need to check if this is still the case and double check the documentation.

**Comment by ataffanel** [comment]
Let's make sure we document that it does not work on apple-silicon Mac and close this issue. I checked again and Virtualbox is still in beta/dev preview. As long as it is the case, we do not support apple-silicon mac with this VM.
